// Achievement definitions — 60 trophies across 7 categories.
//
// Schema:
//   id           unique key
//   category     'combat'|'hero'|'weapon'|'boss'|'mastery'|'meta'|'challenge'
//   tier         'bronze' | 'silver' | 'gold' | 'platinum' — rarity / reward
//   name         human label
//   blurb        flavor description
//   target       value to hit (or boolean condition)
//   icon         sprite name (or icon_* sprite)
//   reward       gold/item granted on unlock
//   secret       bool — hidden until unlocked (no hints)

window.ACHIEVEMENTS = [
  // ─── COMBAT (kill / damage milestones) ──────────────────
  { id: 'kills_100', category: 'combat', tier: 'bronze',
    name: '첫 피',         target: 100,    icon: 'fx_death_generic',
    blurb: '100마리 처치 — 모든 여정의 첫 발걸음.',
    reward: '+50 G' },
  { id: 'kills_1000', category: 'combat', tier: 'silver',
    name: '천 명의 학살자', target: 1000,  icon: 'fx_death_zombie',
    blurb: '1,000마리 처치.',
    reward: '+200 G' },
  { id: 'kills_10000', category: 'combat', tier: 'gold',
    name: '학살의 신',     target: 10000, icon: 'fx_death_skeleton',
    blurb: '10,000마리 처치 — 죽음의 사신과 어깨를 나란히.',
    reward: '+1,000 G · 칭호 「학살자」' },
  { id: 'kills_100000', category: 'combat', tier: 'platinum',
    name: '묘소의 군주',   target: 100000, icon: 'icon_boss_skeleton',
    blurb: '10만 마리 처치. 신화가 된 자.',
    reward: '+10,000 G · 영웅 컬러 변형 해금' },
  { id: 'combo_500', category: 'combat', tier: 'silver',
    name: '연쇄의 흐름',   target: '×500 콤보', icon: 'fx_levelup',
    blurb: '한 런 안에서 500콤보 달성.',
    reward: '+150 G' },
  { id: 'crit_1000', category: 'combat', tier: 'silver',
    name: '치명의 손길',   target: '1000 CRIT', icon: 'fx_impact_slash',
    blurb: '한 런 안에서 크리티컬 1,000번.',
    reward: '+200 G' },
  { id: 'dmg_1m', category: 'combat', tier: 'gold',
    name: '백만의 일격',   target: '1,000,000 누적 피해', icon: 'fx_explosion',
    blurb: '누적 피해 100만 도달.',
    reward: '+800 G' },

  // ─── HERO (unlock + master each character) ──────────────
  { id: 'hero_knight', category: 'hero', tier: 'bronze',
    name: '기사의 길',     target: '튜토리얼 클리어', icon: 'icon_hero_knight',
    blurb: 'Knight로 첫 런 완료.',
    reward: '+100 G' },
  { id: 'hero_warrior', category: 'hero', tier: 'silver',
    name: '광전사의 분노', target: 'Warrior 해금', icon: 'icon_hero_warrior',
    blurb: '챕터 1 클리어로 Warrior 해금.',
    reward: '+200 G · Warrior 콜러 +1' },
  { id: 'hero_mage', category: 'hero', tier: 'silver',
    name: '아케인의 후예', target: 'Mage 해금', icon: 'icon_hero_mage',
    blurb: '챕터 2 클리어로 Mage 해금.',
    reward: '+300 G' },
  { id: 'hero_huntress', category: 'hero', tier: 'silver',
    name: '그림자의 발', target: 'Huntress 해금', icon: 'icon_hero_huntress',
    blurb: '챕터 3 클리어로 Huntress 해금.',
    reward: '+400 G' },
  { id: 'hero_cleric', category: 'hero', tier: 'gold',
    name: '천국의 사도', target: 'Cleric 해금', icon: 'icon_hero_cleric',
    blurb: '챕터 4 + 보스 처치로 Cleric 해금.',
    reward: '+1,000 G' },
  { id: 'hero_lv50', category: 'hero', tier: 'gold',
    name: '50의 경지',   target: '레벨 50 도달', icon: 'fx_levelup',
    blurb: '한 런에서 레벨 50 도달 — 모든 고유 스킬 해금.',
    reward: '+500 G' },
  { id: 'all_heroes_lv50', category: 'hero', tier: 'platinum',
    name: '오대 영웅',   target: '5명 모두 Lv 50', icon: 'icon_hero_cleric',
    blurb: '5명의 영웅 모두로 Lv 50 도달.',
    reward: '+5,000 G · 영웅 골드 변형 해금' },

  // ─── WEAPON (collect + evolve) ──────────────────────────
  { id: 'weapon_first', category: 'weapon', tier: 'bronze',
    name: '첫 무기',     target: '아무 무기 Lv 5', icon: 'icon_wand',
    blurb: '아무 무기든 최대 레벨까지 강화.',
    reward: '+80 G' },
  { id: 'weapon_evolve_1', category: 'weapon', tier: 'silver',
    name: '첫 진화',     target: '진화 1회', icon: 'icon_leg_blade',
    blurb: '기본 무기를 전설로 진화.',
    reward: '+300 G' },
  { id: 'weapon_evolve_5', category: 'weapon', tier: 'gold',
    name: '진화학자',     target: '진화 5종', icon: 'icon_leg_axe',
    blurb: '5가지 다른 진화를 경험.',
    reward: '+1,500 G' },
  { id: 'weapon_evolve_all', category: 'weapon', tier: 'platinum',
    name: '전설의 수집가', target: '진화 17종 전부', icon: 'icon_leg_nova',
    blurb: '17가지 모든 진화를 컴플리트.',
    reward: '+8,000 G · 전설 색상 변형' },
  { id: 'weapon_legendary_drop', category: 'weapon', tier: 'gold',
    name: '운명의 무기', target: '드랍 전용 전설 획득', icon: 'icon_leg_blackhole',
    blurb: '블랙홀 룬 또는 악마의 심장 획득.',
    reward: '+2,000 G' },
  { id: 'weapon_exclusive_all', category: 'weapon', tier: 'gold',
    name: '시그니처 마스터', target: '전용 무기 5종 사용', icon: 'icon_vanguard',
    blurb: '5명의 영웅으로 각자의 전용 무기 사용.',
    reward: '+2,500 G' },

  // ─── BOSS (defeat each) ─────────────────────────────────
  { id: 'boss_skeleton_king', category: 'boss', tier: 'silver',
    name: '왕관 부수기', target: 'Skeleton King 처치', icon: 'icon_boss_skeleton',
    blurb: '챕터 1 보스 — 해골 왕을 무릎 꿇리다.',
    reward: '+500 G' },
  { id: 'boss_vampire', category: 'boss', tier: 'silver',
    name: '뱀파이어 사냥꾼', target: 'Vampire Lord 처치', icon: 'icon_boss_vampire',
    blurb: '챕터 2 보스 — 뱀파이어 로드를 햇볕에.',
    reward: '+800 G' },
  { id: 'boss_demon', category: 'boss', tier: 'gold',
    name: '지옥의 정복자', target: 'Demon 처치', icon: 'icon_boss_demon',
    blurb: '챕터 3 보스 — 데몬을 봉인.',
    reward: '+1,500 G' },
  { id: 'boss_lich', category: 'boss', tier: 'gold',
    name: '리치 슬레이어', target: 'Lich Lord 처치', icon: 'icon_boss_lich',
    blurb: '챕터 4 보스 — 리치를 영혼째 소멸.',
    reward: '+2,500 G' },
  { id: 'boss_all', category: 'boss', tier: 'platinum',
    name: '왕좌의 정복자', target: '4명의 보스 모두 처치', icon: 'icon_boss_lich',
    blurb: '4개 챕터 보스 전원 처치.',
    reward: '+10,000 G · 보스 컬러 변형' },
  { id: 'boss_speedkill', category: 'boss', tier: 'platinum',
    name: '신속한 끝맺음', target: '보스 처치 < 10s', icon: 'icon_haste',
    blurb: '보스 등장 후 10초 안에 처치.',
    reward: '+3,000 G' },

  // ─── MASTERY (use status / synergies / spirits) ─────────
  { id: 'status_5', category: 'mastery', tier: 'bronze',
    name: '디버프 마스터', target: '5종 상태이상 적용', icon: 'status_burn',
    blurb: '한 런에서 5가지 다른 상태이상을 적의 시야에.',
    reward: '+150 G' },
  { id: 'status_all', category: 'mastery', tier: 'gold',
    name: '연금술사',     target: '8종 모두', icon: 'status_freeze',
    blurb: '한 런에서 8가지 상태이상 모두 적용.',
    reward: '+1,200 G' },
  { id: 'synergy_first', category: 'mastery', tier: 'silver',
    name: '첫 시너지',   target: '시너지 1회 발동', icon: 'fx_impact_arcane',
    blurb: 'Shatter / Conduct / Wither 등의 콤보 첫 발동.',
    reward: '+250 G' },
  { id: 'synergy_all', category: 'mastery', tier: 'gold',
    name: '시너지 마스터', target: '시너지 6종 전부', icon: 'fx_chain_lightning',
    blurb: '6가지 시너지 콤보 모두 발동.',
    reward: '+2,000 G' },
  { id: 'spirit_evolve', category: 'mastery', tier: 'silver',
    name: '정령 진화',   target: '정령 1종 3단계', icon: 'spirit_fairy_3',
    blurb: '4가지 정령 중 하나를 3단계까지 진화.',
    reward: '+400 G' },
  { id: 'spirit_all', category: 'mastery', tier: 'platinum',
    name: '대정령사', target: '4종 정령 모두 3단계', icon: 'spirit_fire_3',
    blurb: '4가지 정령 모두 최종 단계로 진화.',
    reward: '+6,000 G' },
  { id: 'banish_5', category: 'mastery', tier: 'silver',
    name: '선택의 자유', target: 'Banish 5회', icon: 'pickup_key',
    blurb: '5번의 무기/패시브 영구 제외.',
    reward: '+300 G' },

  // ─── META (gold / shop / runs) ──────────────────────────
  { id: 'gold_total_10k', category: 'meta', tier: 'bronze',
    name: '구두쇠',     target: '누적 골드 10,000', icon: 'pickup_gold',
    blurb: '런 누적으로 1만 골드 보유.',
    reward: '+200 G' },
  { id: 'gold_total_100k', category: 'meta', tier: 'silver',
    name: '왕의 보고', target: '누적 골드 100,000', icon: 'pickup_chest_gold',
    blurb: '런 누적으로 10만 골드 보유.',
    reward: '+2,000 G' },
  { id: 'shop_upgrade_first', category: 'meta', tier: 'bronze',
    name: '첫 거래',   target: '상점 업그레이드 1회', icon: 'icon_might',
    blurb: '메타 상점에서 첫 업그레이드 구매.',
    reward: '+100 G' },
  { id: 'shop_all_combat', category: 'meta', tier: 'gold',
    name: '전투 시너지', target: '전투 4종 MAX', icon: 'icon_might',
    blurb: '상점 전투 탭 4가지 모두 최대 레벨.',
    reward: '+3,000 G' },
  { id: 'shop_all_max', category: 'meta', tier: 'platinum',
    name: '완벽한 준비', target: '모든 업그레이드 MAX', icon: 'icon_leg_blade',
    blurb: '상점 14가지 업그레이드 모두 최대.',
    reward: '+20,000 G · 영웅 다이아 변형' },
  { id: 'runs_10', category: 'meta', tier: 'bronze',
    name: '경험자',   target: '10회 클리어', icon: 'fx_levelup',
    blurb: '10번의 성공적인 런 완료.',
    reward: '+500 G' },
  { id: 'runs_100', category: 'meta', tier: 'gold',
    name: '백전노장', target: '100회 클리어', icon: 'icon_haste',
    blurb: '100번의 성공적인 런 완료.',
    reward: '+5,000 G' },

  // ─── CHALLENGE (hard conditions) ────────────────────────
  { id: 'no_damage_2m', category: 'challenge', tier: 'gold',
    name: '무결한 시작', target: '2분간 피해 0', icon: 'status_shield',
    blurb: '런 시작부터 2분간 피해를 받지 않는다.',
    reward: '+1,500 G' },
  { id: 'no_damage_run', category: 'challenge', tier: 'platinum',
    name: '신의 가호',   target: '런 전체 피해 0', icon: 'icon_hero_cleric',
    blurb: '30분 런 동안 한 번도 피해를 받지 않는다.',
    reward: '+15,000 G · 칭호 「불멸」', secret: true },
  { id: 'no_passive', category: 'challenge', tier: 'gold',
    name: '순수 무기',   target: '패시브 0개 런 클리어', icon: 'icon_might',
    blurb: '패시브를 한 번도 뽑지 않고 런 클리어.',
    reward: '+2,500 G' },
  { id: 'one_weapon', category: 'challenge', tier: 'gold',
    name: '외길 인생',   target: '무기 1종만 사용', icon: 'icon_wand',
    blurb: '시작 무기 1개로만 런 클리어.',
    reward: '+3,000 G' },
  { id: 'one_hp', category: 'challenge', tier: 'platinum',
    name: '한 발의 의지', target: 'HP 1로 보스 처치', icon: 'pickup_heart',
    blurb: 'HP 1 상태에서 보스 처치.',
    reward: '+5,000 G', secret: true },
  { id: 'speedrun', category: 'challenge', tier: 'platinum',
    name: '신속한 정복', target: '챕터 15분 내 클리어', icon: 'icon_swift',
    blurb: '챕터 보스를 15분 안에 처치.',
    reward: '+4,000 G' },
  { id: 'pacifist', category: 'challenge', tier: 'platinum',
    name: '평화주의자',   target: '5분간 처치 0', icon: 'status_shield',
    blurb: '런 시작 5분간 적을 한 마리도 처치하지 않고 생존.',
    reward: '+3,500 G', secret: true },
  { id: 'all_status_one_enemy', category: 'challenge', tier: 'gold',
    name: '디버프 콤보',   target: '한 적에 4상태이상', icon: 'status_poison',
    blurb: '한 적에게 동시에 4가지 상태이상 적용.',
    reward: '+1,800 G' },

  // ─── HIDDEN / SECRET ────────────────────────────────────
  { id: 'secret_konami', category: 'challenge', tier: 'platinum',
    name: '???',        target: '???', icon: 'pickup_rune',
    blurb: '오직 자신만이 안다.',
    reward: '???', secret: true },
  { id: 'secret_pet', category: 'challenge', tier: 'gold',
    name: '???',        target: '???', icon: 'pickup_rune',
    blurb: '오직 자신만이 안다.',
    reward: '???', secret: true },
  { id: 'secret_dance', category: 'challenge', tier: 'silver',
    name: '???',        target: '???', icon: 'pickup_rune',
    blurb: '오직 자신만이 안다.',
    reward: '???', secret: true },

  // ─── STAGE-specific extras ──────────────────────────────
  { id: 'stage_perfect_crypt', category: 'mastery', tier: 'silver',
    name: '묘소 정복자',   target: '챕터 1 무피격 클리어', icon: 'icon_boss_skeleton',
    blurb: '챕터 1을 한 번도 피해받지 않고 클리어.',
    reward: '+1,000 G' },
  { id: 'stage_perfect_forest', category: 'mastery', tier: 'gold',
    name: '숲의 그림자',   target: '챕터 2 무피격 클리어', icon: 'icon_boss_vampire',
    blurb: '챕터 2를 한 번도 피해받지 않고 클리어.',
    reward: '+2,000 G' },
  { id: 'stage_perfect_volcano', category: 'mastery', tier: 'gold',
    name: '용암의 지배자', target: '챕터 3 무피격 클리어', icon: 'icon_boss_demon',
    blurb: '챕터 3를 한 번도 피해받지 않고 클리어.',
    reward: '+3,000 G' },
  { id: 'stage_perfect_ice', category: 'mastery', tier: 'platinum',
    name: '얼음의 주인',   target: '챕터 4 무피격 클리어', icon: 'icon_boss_lich',
    blurb: '챕터 4를 한 번도 피해받지 않고 클리어.',
    reward: '+5,000 G' },
];

window.ACHIEVEMENT_CATEGORIES = [
  { id: 'combat',    name: '전투',     icon: 'fx_death_generic' },
  { id: 'hero',      name: '영웅',     icon: 'icon_hero_knight' },
  { id: 'weapon',    name: '무기',     icon: 'icon_leg_blade' },
  { id: 'boss',      name: '보스',     icon: 'icon_boss_lich' },
  { id: 'mastery',   name: '숙련',     icon: 'status_burn' },
  { id: 'meta',      name: '메타',     icon: 'pickup_gold' },
  { id: 'challenge', name: '도전',     icon: 'icon_swift' },
];

window.ACHIEVEMENT_TIERS = {
  bronze:   { name: 'BRONZE',   color: '#c68b4a' },
  silver:   { name: 'SILVER',   color: '#b4a5b8' },
  gold:     { name: 'GOLD',     color: '#f0d27a' },
  platinum: { name: 'PLATINUM', color: '#49d0e0' },
};
