// Stage / chapter definitions — biome, enemies, boss, music vibe.

window.STAGES = [
  {
    id: 'crypt', chapter: 1, name: '망자의 묘소',
    biome: 'dungeon',
    tile_pool: ['tile_stone_1', 'tile_stone_2', 'tile_stone_crack', 'tile_bones', 'tile_blood', 'tile_moss'],
    enemies: ['crypt_archer', 'crypt_wraith', 'crypt_bone_pile', 'walker_walk', 'runner_walk'],
    elite: ['elite_walk', 'crypt_keeper'],
    boss: 'boss_skeleton_king',
    boss_name: '해골 왕',
    duration: 30,
    accent: '#8d83a0',
    blurb: '오래된 지하 묘소. 잠들지 못한 망자들이 깨어난다.',
    unlock_condition: '기본 해금',
    rewards: ['+800 gold', 'Warrior 해금'],
  },
  {
    id: 'forest', chapter: 2, name: '저주받은 숲',
    biome: 'outdoor',
    tile_pool: ['tile_grass_full', 'tile_grass_dark', 'tile_dirt', 'tile_grass', 'tile_moss'],
    enemies: ['forest_wolf', 'forest_vine', 'forest_owl', 'bat_fly', 'spider_walk'],
    elite: ['forest_treant', 'brute_walk'],
    boss: 'boss_vampire',
    boss_name: '뱀파이어 로드',
    duration: 30,
    accent: '#88b85a',
    blurb: '안개와 그림자가 짙은 고대 숲. 밤이 영원하다.',
    unlock_condition: '챕터 1 클리어',
    rewards: ['+2000 gold', 'Mage 해금'],
  },
  {
    id: 'volcano', chapter: 3, name: '화산 분지',
    biome: 'volcano',
    tile_pool: ['tile_volcano_rock', 'tile_volcano_ash', 'tile_volcano_lava'],
    enemies: ['volcano_imp', 'volcano_slug', 'volcano_ash', 'runner_walk'],
    elite: ['volcano_brute', 'chimera_walk'],
    boss: 'boss_pyrolord',
    boss_name: '데몬',
    duration: 30,
    accent: '#f08a2a',
    blurb: '용암이 흐르는 지옥의 입구. 데몬이 잠에서 깨어났다.',
    unlock_condition: '챕터 2 클리어',
    rewards: ['+4000 gold', 'Huntress 해금'],
  },
  {
    id: 'ice_cavern', chapter: 4, name: '얼음 동굴',
    biome: 'ice',
    tile_pool: ['tile_ice_floor', 'tile_ice_crack', 'tile_ice_snow'],
    enemies: ['ice_wisp', 'ice_spider', 'bat_fly', 'runner_walk'],
    elite: ['ice_golem', 'ice_frost_lich'],
    boss: 'boss_frost_dragon',
    boss_name: '리치 로드',
    duration: 35,
    accent: '#6fb4dc',
    blurb: '영원히 얼어붙은 동굴. 리치가 마법의 결정 위에 앉아있다.',
    unlock_condition: '챕터 3 클리어',
    rewards: ['+8000 gold', 'Cleric 해금'],
  },
];
