// Weapon definitions — DATA only.
// Behaviour/action profiles for every weapon in the pack. The art is in
// art/sprites.js; this file says "how does it act" so the game engine can
// import a single source of truth.
//
// Schema per entry:
//   tier:         'basic' | 'legendary'
//   name:         human label
//   icon:         sprite name for the 24×24 UI icon
//   sprite:       sprite name of the in-world projectile/weapon
//   pattern:      'arc' | 'fan' | 'ring' | 'orbit' | 'aimed' | 'volley'
//                 | 'beam' | 'aoe' | 'rain' | 'chain' | 'boomerang'
//                 | 'spiral' | 'static' | 'summon' | 'lash' | 'pull'
//   count:        # projectiles per cast (optional)
//   pierce:       enemies pierced (999 = infinite, optional)
//   bounces:      chain bounces (chain pattern, optional)
//   homing:       bool — projectile turns toward nearest enemy
//   knockback:    px applied on hit (optional)
//   duration:     seconds the effect persists (aoe/beam patterns)
//   radius:       px AoE / pull radius
//   proc_chance:  0..1 chance the proc_fx triggers per hit
//   blurb:        flavor + behaviour summary shown in the workbench
//   tags:         visual category — 'physical' | 'fire' | 'ice' | 'holy'
//                 | 'arcane' | 'shadow' | 'nature' | 'lightning'
//
//   FX hooks (sprite names that play at each phase of the cast):
//     action_fx — large background flourish shown while casting/swinging
//     cast_fx   — pre-shot anticipation (summon circle, glow)
//     muzzle_fx — flash where the projectile leaves the player
//     trail_fx  — clip drawn behind moving projectile
//     impact_fx — clip on hit
//     proc_fx   — clip when the proc_chance triggers
//     aoe_fx    — for area attacks, the ground effect that lingers
//     drain_fx  — for life-drain weapons, the visual link to the player
//     death_fx  — clip when killed enemies are consumed (necro etc.)

window.WEAPONS = {
  // ──────────────────────────────────────────────────────────────
  // BASIC — 11 starting / common-pool weapons
  // ──────────────────────────────────────────────────────────────
  wand: {
    tier: 'basic', name: '매직 완드',
    icon: 'icon_wand', sprite: 'proj_wand',
    pattern: 'aimed', count: 1, pierce: 1,
    homing: true, knockback: 7,
    blurb: '가장 가까운 적을 향해 마법 탄환을 발사. 시작 무기.',
    tags: ['arcane'],
    cast_fx: 'fx_muzzle_arcane',
    muzzle_fx: 'fx_muzzle_arcane',
    trail_fx: 'trail_proj',
    impact_fx: 'fx_impact_arcane',
  },
  nova: {
    tier: 'basic', name: '노바',
    icon: 'icon_nova', sprite: 'proj_nova',
    pattern: 'ring', count: 8, pierce: 1,
    knockback: 5, radius: 80,
    blurb: '플레이어를 중심으로 8방향 마법 구체를 방출.',
    tags: ['arcane'],
    action_fx: 'fx_summon_circle',
    cast_fx: 'fx_muzzle_arcane',
    impact_fx: 'fx_impact_arcane',
  },
  prism: {
    tier: 'basic', name: '프리즘',
    icon: 'icon_prism', sprite: 'proj_prism',
    pattern: 'fan', count: 3, pierce: 3,
    homing: false, knockback: 9,
    blurb: '얼음 결정 3발을 부채꼴로 발사, 3번 관통.',
    tags: ['ice', 'arcane'],
    muzzle_fx: 'fx_muzzle_arcane',
    impact_fx: 'fx_impact_arcane',
    proc_fx: 'status_freeze', proc_chance: 0.25,
  },
  spear: {
    tier: 'basic', name: '창',
    icon: 'icon_spear', sprite: 'proj_spear',
    pattern: 'aimed', count: 1, pierce: 999,
    knockback: 4,
    blurb: '직선으로 찔러 모든 적을 관통. 짧은 사거리, 빠른 회복.',
    tags: ['physical'],
    action_fx: 'fx_swing',
    impact_fx: 'fx_impact_pierce',
  },
  axe: {
    tier: 'basic', name: '도끼',
    icon: 'icon_axe', sprite: 'proj_axe',
    pattern: 'boomerang', count: 2, pierce: 999,
    knockback: 12,
    blurb: '회전하는 도끼를 던져 돌아오기까지 모든 적을 베어버린다.',
    tags: ['physical'],
    action_fx: 'fx_boomerang_arc',
    trail_fx: 'trail_slash_arc',
    impact_fx: 'fx_impact_slash',
  },
  mace: {
    tier: 'basic', name: '철퇴',
    icon: 'icon_mace', sprite: 'proj_mace',
    pattern: 'orbit', count: 1, pierce: 999,
    knockback: 18, radius: 32,
    blurb: '플레이어 주위를 도는 철퇴. 닿는 모든 적에게 둔기 피해.',
    tags: ['physical'],
    action_fx: 'fx_whirlwind',
    impact_fx: 'fx_impact_smash',
  },
  holywater: {
    tier: 'basic', name: '성수병',
    icon: 'icon_holywater', sprite: 'proj_holywater',
    pattern: 'aoe', count: 1, duration: 3, radius: 40,
    blurb: '성수병을 던져 깨진 자리에 신성한 웅덩이를 만든다.',
    tags: ['holy'],
    cast_fx: 'fx_muzzle_holy',
    impact_fx: 'fx_impact_splash',
    aoe_fx: 'fx_holywater_splash',
  },
  arrow: {
    tier: 'basic', name: '화살',
    icon: 'icon_arrow', sprite: 'proj_arrow',
    pattern: 'aimed', count: 1, pierce: 2,
    homing: false, knockback: 3,
    blurb: '직선 화살. 빠른 사거리, 적중 시 짧은 출혈.',
    tags: ['physical'],
    muzzle_fx: 'fx_muzzle_arcane',
    trail_fx: 'trail_arrow',
    impact_fx: 'fx_impact_pierce',
    proc_fx: 'status_bleed', proc_chance: 0.15,
  },
  garlic: {
    tier: 'basic', name: '마늘',
    icon: 'icon_garlic', sprite: 'proj_garlic',
    pattern: 'static', radius: 48, pierce: 999,
    blurb: '플레이어 주위에 항상 발동하는 신성 오라. 접촉 적을 태운다.',
    tags: ['holy', 'nature'],
    aoe_fx: 'fx_heal_aura',
    impact_fx: 'fx_impact_holy',
  },
  bible: {
    tier: 'basic', name: '성서',
    icon: 'icon_bible', sprite: 'proj_bible',
    pattern: 'orbit', count: 1, pierce: 999,
    radius: 64,
    blurb: '플레이어 주위를 도는 펼친 성서. 닿는 적을 정화한다.',
    tags: ['holy'],
    impact_fx: 'fx_impact_holy',
  },
  cross: {
    tier: 'basic', name: '십자가',
    icon: 'icon_cross', sprite: 'proj_cross',
    pattern: 'boomerang', count: 1, pierce: 999,
    blurb: '회전하는 십자가가 돌아온다. 부메랑처럼 두 번 베어버린다.',
    tags: ['holy'],
    action_fx: 'fx_boomerang_arc',
    impact_fx: 'fx_impact_holy',
  },

  // ──────────────────────────────────────────────────────────────
  // EXTRA — 6 advanced common weapons
  // ──────────────────────────────────────────────────────────────
  whip: {
    tier: 'basic', name: '채찍',
    icon: 'icon_whip', sprite: 'proj_whip',
    pattern: 'lash', count: 1, pierce: 999,
    knockback: 14,
    blurb: '플레이어 양옆을 빠르게 후려친다. 좁고 길게 뻗는 라인.',
    tags: ['physical'],
    action_fx: 'fx_impact_lash',
    impact_fx: 'fx_impact_lash',
  },
  lightning: {
    tier: 'basic', name: '낙뢰',
    icon: 'icon_lightning', sprite: 'proj_lightning',
    pattern: 'chain', count: 1, bounces: 3,
    blurb: '근처 적에게 번개를 떨어뜨려 인접 적으로 연쇄 도약.',
    tags: ['lightning'],
    cast_fx: 'fx_summon_circle',
    impact_fx: 'fx_impact_arcane',
    proc_fx: 'fx_chain_lightning', proc_chance: 1,
  },
  firewall: {
    tier: 'basic', name: '화염벽',
    icon: 'icon_firewall', sprite: 'proj_firewall',
    pattern: 'aoe', count: 1, duration: 5, radius: 60,
    blurb: '땅에 화염벽을 펼쳐 안에 머무는 적에게 지속 화상.',
    tags: ['fire'],
    aoe_fx: 'fx_impact_scorch',
    impact_fx: 'fx_impact_scorch',
    proc_fx: 'status_burn', proc_chance: 1,
  },
  knives: {
    tier: 'basic', name: '단검 투척',
    icon: 'icon_knives', sprite: 'proj_knives',
    pattern: 'fan', count: 5, pierce: 1,
    blurb: '5자루의 단검을 부채꼴로 던진다. 빠른 회복.',
    tags: ['physical'],
    action_fx: 'fx_fan_burst',
    impact_fx: 'fx_impact_pierce',
    proc_fx: 'status_bleed', proc_chance: 0.2,
  },
  scythe: {
    tier: 'basic', name: '낫',
    icon: 'icon_scythe', sprite: 'proj_scythe',
    pattern: 'arc', count: 1, pierce: 999,
    knockback: 10,
    blurb: '거대한 낫을 휘둘러 앞 호 영역을 일망타진.',
    tags: ['shadow', 'physical'],
    action_fx: 'fx_swing',
    impact_fx: 'fx_impact_slash',
    proc_fx: 'status_bleed', proc_chance: 0.3,
  },
  bone: {
    tier: 'basic', name: '뼈 파편',
    icon: 'icon_bone', sprite: 'proj_bone',
    pattern: 'volley', count: 3, pierce: 2,
    blurb: '뼈 파편 3개를 호선으로 발사. 적을 쓰러뜨리면 추가 파편 발사.',
    tags: ['shadow'],
    impact_fx: 'fx_impact_pierce',
    death_fx: 'fx_death_skeleton',
  },

  // ──────────────────────────────────────────────────────────────
  // LEGENDARY — drops & evolutions with unique actions
  // ──────────────────────────────────────────────────────────────
  leg_blade: {
    tier: 'legendary', name: '여명의 검기',
    icon: 'icon_leg_blade', sprite: 'proj_leg_blade',
    pattern: 'beam', count: 1, pierce: 999,
    duration: 0.3, knockback: 8,
    blurb: '검을 휘두를 때마다 검기를 발사 — 모든 적 관통. 빠른 회복, 짧은 사거리.',
    tags: ['holy', 'physical'],
    action_fx: 'fx_swing',
    cast_fx: 'fx_muzzle_holy',
    trail_fx: 'trail_slash_arc',
    impact_fx: 'fx_impact_slash',
  },
  leg_axe: {
    tier: 'legendary', name: '폭풍 도끼',
    icon: 'icon_leg_axe', sprite: 'proj_leg_axe',
    pattern: 'boomerang', count: 3, pierce: 999,
    knockback: 16,
    blurb: '천둥을 두른 도끼 3자루가 회전 부메랑으로 적을 가르며 돌아온다.',
    tags: ['physical', 'lightning'],
    action_fx: 'fx_boomerang_arc',
    impact_fx: 'fx_impact_smash',
    proc_fx: 'fx_chain_lightning', proc_chance: 0.25,
  },
  leg_spear: {
    tier: 'legendary', name: '미스릴 할버드',
    icon: 'icon_leg_spear', sprite: 'proj_leg_spear',
    pattern: 'beam', count: 1, pierce: 999,
    duration: 0.4, knockback: 6,
    blurb: '미스릴 창의 일직선 관통 일격. 라인 위 모든 적을 한 번에 꿰뚫는다.',
    tags: ['holy', 'physical'],
    action_fx: 'fx_beam',
    impact_fx: 'fx_impact_pierce',
  },
  leg_arrow: {
    tier: 'legendary', name: '은룡의 화살',
    icon: 'icon_leg_arrow', sprite: 'proj_leg_arrow',
    pattern: 'aimed', count: 1, pierce: 5,
    homing: true,
    blurb: '은룡 화살이 호밍으로 추적. 적중 시 짧은 폭발로 인접 적 산화.',
    tags: ['holy', 'physical'],
    muzzle_fx: 'fx_muzzle_holy',
    trail_fx: 'trail_arrow',
    impact_fx: 'fx_impact_pierce',
    proc_fx: 'fx_explosion', proc_chance: 1,
  },
  leg_whip: {
    tier: 'legendary', name: '강철 사슬 채찍',
    icon: 'icon_leg_whip', sprite: 'proj_leg_whip',
    pattern: 'lash', count: 1, pierce: 999,
    knockback: 22, duration: 0.4,
    blurb: '강철 사슬이 채찍 라인 끝에 부착돼 적을 끌어당긴다.',
    tags: ['physical'],
    action_fx: 'fx_impact_lash',
    impact_fx: 'fx_impact_lash',
    proc_fx: 'fx_vortex', proc_chance: 1,
  },
  leg_cross: {
    tier: 'legendary', name: '작열 십자가',
    icon: 'icon_leg_cross', sprite: 'proj_leg_cross',
    pattern: 'boomerang', count: 3, pierce: 999,
    blurb: '3개의 불타는 십자가가 다른 궤도로 회전, 부메랑처럼 돌아온다.',
    tags: ['holy', 'fire'],
    action_fx: 'fx_boomerang_arc',
    impact_fx: 'fx_impact_holy',
    proc_fx: 'status_burn', proc_chance: 0.4,
  },
  leg_bible: {
    tier: 'legendary', name: '성광서',
    icon: 'icon_leg_bible', sprite: 'proj_leg_bible',
    pattern: 'orbit', count: 4, pierce: 999,
    radius: 72,
    blurb: '4권의 성서가 두 겹의 궤도로 플레이어를 호위. 닿는 적에게 정화 피해.',
    tags: ['holy'],
    impact_fx: 'fx_impact_holy',
    proc_fx: 'status_shield', proc_chance: 0.1,
  },
  leg_scythe: {
    tier: 'legendary', name: '사신의 낫',
    icon: 'icon_scythe', sprite: 'proj_leg_scythe',
    pattern: 'arc', count: 1, pierce: 999,
    knockback: 12,
    blurb: '거대한 사신 낫. 처치한 적의 영혼을 흡수해 플레이어 체력 회복.',
    tags: ['shadow'],
    action_fx: 'fx_swing',
    impact_fx: 'fx_impact_slash',
    drain_fx: 'fx_soul_wisp',
    death_fx: 'fx_soul_wisp',
    proc_chance: 0.15,
  },
  leg_nova: {
    tier: 'legendary', name: '황금 태양',
    icon: 'icon_leg_nova', sprite: 'proj_leg_nova',
    pattern: 'ring', count: 12, pierce: 3,
    radius: 100, knockback: 6,
    blurb: '12방향으로 황금빛 태양 광선 방출. 닿는 적에 화상 + 신성 피해.',
    tags: ['holy', 'fire'],
    action_fx: 'fx_summon_circle',
    cast_fx: 'fx_muzzle_holy',
    impact_fx: 'fx_impact_holy',
    proc_fx: 'status_burn', proc_chance: 0.5,
  },

  // ─── Unique-action legendaries (drops, not evolutions) ───
  leg_spectral_bow: {
    tier: 'legendary', name: '유령의 활',
    icon: 'icon_leg_spectral_bow', sprite: 'proj_leg_spectral_bow',
    pattern: 'volley', count: 8, pierce: 1,
    homing: true,
    blurb: '하늘에서 유령 화살 8발이 적을 추적. 발사 위치는 적 머리 위.',
    tags: ['shadow', 'arcane'],
    cast_fx: 'fx_summon_circle',
    muzzle_fx: 'fx_muzzle_arcane',
    impact_fx: 'fx_impact_arcane',
    proc_fx: 'status_freeze', proc_chance: 0.18,
  },
  leg_tempest: {
    tier: 'legendary', name: '템페스트 해머',
    icon: 'icon_leg_tempest', sprite: 'proj_leg_tempest',
    pattern: 'aoe', count: 1, duration: 4, radius: 120,
    knockback: 24,
    blurb: '거대 해머가 땅을 내리쳐 폭풍 전역에 연쇄 번개 + 강한 넉백.',
    tags: ['lightning', 'physical'],
    action_fx: 'fx_swing',
    cast_fx: 'fx_summon_circle',
    impact_fx: 'fx_impact_smash',
    aoe_fx: 'fx_chain_lightning',
    proc_fx: 'status_shock', proc_chance: 0.6,
  },
  leg_necro_skull: {
    tier: 'legendary', name: '네크로 스쿨',
    icon: 'icon_leg_necro', sprite: 'proj_leg_necro_skull',
    pattern: 'summon', count: 2, pierce: 999,
    duration: 8,
    blurb: '플레이어를 따라다니는 두개골 2개를 소환. 자동 사격으로 적 공격.',
    tags: ['shadow'],
    cast_fx: 'fx_summon_circle',
    action_fx: 'fx_soul_wisp',
    impact_fx: 'fx_impact_arcane',
    death_fx: 'fx_soul_wisp',
  },
  leg_black_hole: {
    tier: 'legendary', name: '블랙홀 룬',
    icon: 'icon_leg_blackhole', sprite: 'proj_leg_black_hole',
    pattern: 'pull', count: 1, duration: 2.5, radius: 96,
    blurb: '땅에 검은 구를 떨궈 모든 적을 빨아들이고 폭발. 보스도 잠시 끌린다.',
    tags: ['shadow', 'arcane'],
    action_fx: 'fx_vortex',
    cast_fx: 'fx_summon_circle',
    aoe_fx: 'fx_vortex',
    impact_fx: 'fx_explosion',
    proc_fx: 'status_stun', proc_chance: 1,
  },
  leg_soul_lantern: {
    tier: 'legendary', name: '영혼의 등',
    icon: 'icon_leg_soul_lantern', sprite: 'proj_leg_soul_lantern',
    pattern: 'orbit', count: 2, pierce: 999,
    radius: 56,
    blurb: '영혼 등불이 주위를 돈다. 처치한 적은 등불에 흡수되어 플레이어를 치유.',
    tags: ['holy', 'shadow'],
    action_fx: 'fx_heal_aura',
    impact_fx: 'fx_impact_holy',
    drain_fx: 'fx_soul_wisp',
    death_fx: 'fx_soul_wisp',
    proc_chance: 0.25,
  },

  // ─── v3 legendaries ───
  leg_sun_phoenix: {
    tier: 'legendary', name: '태양의 봉황활',
    icon: 'icon_leg_arrow', sprite: 'proj_leg_sun_phoenix',
    pattern: 'aimed', count: 1, pierce: 999,
    homing: true,
    blurb: '봉황 화살이 일직선으로 모든 적을 관통. 적중 자리에 화염 깃털을 떨군다.',
    tags: ['fire', 'holy'],
    muzzle_fx: 'fx_muzzle_fire',
    trail_fx: 'trail_arrow',
    impact_fx: 'fx_impact_scorch',
    aoe_fx: 'fx_impact_scorch',
    proc_fx: 'status_burn', proc_chance: 0.8,
  },
  leg_eternal_frost: {
    tier: 'legendary', name: '영원의 빙결',
    icon: 'icon_leg_blade', sprite: 'proj_leg_eternal_frost',
    pattern: 'beam', count: 1, pierce: 999,
    duration: 0.5,
    blurb: '빙결 검기 한 줄로 라인 위 모든 적을 얼린다. 동결된 적은 추가 피해.',
    tags: ['ice', 'arcane'],
    action_fx: 'fx_swing',
    cast_fx: 'fx_muzzle_arcane',
    impact_fx: 'fx_impact_arcane',
    proc_fx: 'status_freeze', proc_chance: 1,
  },
  leg_demon_heart: {
    tier: 'legendary', name: '악마의 심장',
    icon: 'icon_leg_nova', sprite: 'proj_leg_demon_heart',
    pattern: 'aoe', count: 1, duration: 6, radius: 80,
    blurb: '심장을 떨궈 핏빛 영역 생성. 안에 머무는 적의 체력을 흡수해 플레이어 회복.',
    tags: ['shadow', 'fire'],
    action_fx: 'fx_summon_circle',
    aoe_fx: 'fx_vortex',
    impact_fx: 'fx_impact_arcane',
    drain_fx: 'fx_soul_wisp',
    proc_fx: 'status_bleed', proc_chance: 0.5,
  },
  leg_storm_caller: {
    tier: 'legendary', name: '폭풍 소환자',
    icon: 'icon_leg_tempest', sprite: 'proj_leg_storm_caller',
    pattern: 'rain', count: 6, pierce: 999,
    duration: 3, radius: 120,
    blurb: '하늘에서 번개 6대가 무작위로 떨어진다. 화면 전체가 전장이 된다.',
    tags: ['lightning'],
    cast_fx: 'fx_summon_circle',
    aoe_fx: 'fx_chain_lightning',
    impact_fx: 'fx_impact_arcane',
    proc_fx: 'status_shock', proc_chance: 1,
  },
  leg_world_tree: {
    tier: 'legendary', name: '세계수의 가지',
    icon: 'icon_leg_bible', sprite: 'proj_leg_world_tree',
    pattern: 'static', radius: 64, pierce: 999,
    duration: 999,
    blurb: '플레이어 발 밑에 세계수 뿌리가 솟아나 주위 적을 끊임없이 가시로 찌른다.',
    tags: ['nature', 'holy'],
    aoe_fx: 'fx_ground_spike',
    impact_fx: 'fx_impact_pierce',
    proc_fx: 'status_poison', proc_chance: 0.4,
  },
  // ──────────────────────────────────────────────────────────────
  // CHARACTER-EXCLUSIVE WEAPONS — each hero owns one
  // ──────────────────────────────────────────────────────────────
  vanguard_sword: {
    tier: 'basic', name: '선봉의 검', exclusive: 'knight',
    icon: 'icon_vanguard', sprite: 'proj_vanguard_sword',
    pattern: 'arc', count: 1, pierce: 999, knockback: 10,
    blurb: '기사의 광폭 검기. 앞쪽 호 영역의 모든 적을 한 번에 베어버린다.',
    tags: ['holy', 'physical'],
    action_fx: 'fx_swing',
    trail_fx: 'trail_slash_arc',
    impact_fx: 'fx_impact_slash',
    proc_fx: 'status_shield', proc_chance: 0.1,
  },
  warhammer: {
    tier: 'basic', name: '전쟁 망치', exclusive: 'warrior',
    icon: 'icon_warhammer', sprite: 'proj_warhammer',
    pattern: 'aoe', count: 1, radius: 64, duration: 0.4, knockback: 28,
    blurb: '전사의 거대 해머. 땅을 내리쳐 광역 충격파 + 강한 넉백.',
    tags: ['physical'],
    action_fx: 'fx_swing',
    cast_fx: 'fx_summon_circle',
    impact_fx: 'fx_impact_smash',
    aoe_fx: 'fx_bash',
    proc_fx: 'status_stun', proc_chance: 0.35,
  },
  astral_staff: {
    tier: 'basic', name: '아스트랄 지팡이', exclusive: 'mage',
    icon: 'icon_astral_staff', sprite: 'proj_astral_staff',
    pattern: 'volley', count: 4, pierce: 2, homing: true,
    blurb: '마법사의 추적 마법구 4개. 각자 가장 가까운 적을 추적해 폭발.',
    tags: ['arcane'],
    cast_fx: 'fx_summon_circle',
    muzzle_fx: 'fx_muzzle_arcane',
    trail_fx: 'trail_proj',
    impact_fx: 'fx_impact_arcane',
    proc_fx: 'fx_explosion', proc_chance: 0.2,
  },
  hunters_bow: {
    tier: 'basic', name: '사냥꾼의 활', exclusive: 'huntress',
    icon: 'icon_hunters_bow', sprite: 'proj_hunters_bow',
    pattern: 'fan', count: 3, pierce: 3, knockback: 4,
    blurb: '궁수의 3연사 일제 사격. 빠른 회복 + 깊은 관통.',
    tags: ['physical'],
    action_fx: 'fx_fan_burst',
    muzzle_fx: 'fx_muzzle_arcane',
    trail_fx: 'trail_arrow',
    impact_fx: 'fx_impact_pierce',
    proc_fx: 'status_bleed', proc_chance: 0.3,
  },
  holy_censer: {
    tier: 'basic', name: '신성 향로', exclusive: 'cleric',
    icon: 'icon_holy_censer', sprite: 'proj_holy_censer',
    pattern: 'orbit', count: 2, pierce: 999, radius: 56,
    blurb: '성직자의 흔드는 향로 2개. 닿는 적을 정화하고 향 자국을 남겨 플레이어 회복.',
    tags: ['holy'],
    action_fx: 'fx_heal_aura',
    impact_fx: 'fx_impact_holy',
    drain_fx: 'fx_soul_wisp',
    aoe_fx: 'fx_heal_aura',
    proc_fx: 'status_shield', proc_chance: 0.15,
  },

  // ──────────────────────────────────────────────────────────────
  // KNIGHT'S THEMED WEAPONS (3 extra)
  // ──────────────────────────────────────────────────────────────
  shield_throw: {
    tier: 'basic', name: '방패 투척', exclusive: 'knight',
    icon: 'icon_shield_throw', sprite: 'proj_shield_throw',
    pattern: 'boomerang', count: 1, pierce: 999, knockback: 14,
    blurb: '회전하며 돌아오는 황금 방패. 모든 적 관통 + 부메랑처럼 복귀.',
    tags: ['holy', 'physical'],
    action_fx: 'fx_boomerang_arc',
    trail_fx: 'trail_slash_arc',
    impact_fx: 'fx_impact_smash',
    proc_fx: 'status_shield', proc_chance: 0.15,
  },
  divine_hammer: {
    tier: 'basic', name: '신성 망치', exclusive: 'knight',
    icon: 'icon_divine_hammer', sprite: 'proj_divine_hammer',
    pattern: 'aoe', count: 1, radius: 56, duration: 0.5, knockback: 22,
    blurb: '하늘에서 떨어지는 신성 망치. 적중 시 광역 충격 + 화상 / 스턴.',
    tags: ['holy', 'physical'],
    action_fx: 'fx_summon_circle',
    cast_fx: 'fx_muzzle_holy',
    impact_fx: 'fx_impact_smash',
    aoe_fx: 'fx_bash',
    proc_fx: 'status_stun', proc_chance: 0.5,
  },
  holy_lance: {
    tier: 'basic', name: '신성 창', exclusive: 'knight',
    icon: 'icon_holy_lance', sprite: 'proj_holy_lance',
    pattern: 'beam', count: 1, pierce: 999, duration: 0.3,
    blurb: '직선 빛의 창. 라인 위 모든 적을 관통하며 빠르게 회복.',
    tags: ['holy', 'physical'],
    action_fx: 'fx_beam',
    impact_fx: 'fx_impact_pierce',
    proc_fx: 'status_burn', proc_chance: 0.2,
  },

  // ──────────────────────────────────────────────────────────────
  // WARRIOR'S THEMED WEAPONS (3 extra)
  // ──────────────────────────────────────────────────────────────
  cleaver: {
    tier: 'basic', name: '대형 클리버', exclusive: 'warrior',
    icon: 'icon_cleaver', sprite: 'proj_cleaver',
    pattern: 'arc', count: 1, pierce: 3, knockback: 16,
    blurb: '거대한 도살용 칼. 앞쪽 호를 통째로 베어버린다 + 깊은 출혈.',
    tags: ['physical'],
    action_fx: 'fx_swing',
    impact_fx: 'fx_impact_slash',
    proc_fx: 'status_bleed', proc_chance: 0.5,
  },
  chain_flail: {
    tier: 'basic', name: '쇠사슬 철구', exclusive: 'warrior',
    icon: 'icon_chain_flail', sprite: 'proj_chain_flail',
    pattern: 'orbit', count: 2, pierce: 999, radius: 72, knockback: 18,
    blurb: '플레이어를 도는 가시 박힌 철구 2개. 닿는 적에게 강한 둔기 피해 + 스턴.',
    tags: ['physical'],
    action_fx: 'fx_whirlwind',
    impact_fx: 'fx_impact_smash',
    proc_fx: 'status_stun', proc_chance: 0.3,
  },
  throw_axes: {
    tier: 'basic', name: '연쇄 도끼 투척', exclusive: 'warrior',
    icon: 'icon_throw_axes', sprite: 'proj_throw_axes',
    pattern: 'fan', count: 5, pierce: 2, knockback: 8,
    blurb: '5자루의 작은 도끼를 부채꼴로 던진다. 출혈 + 넉백.',
    tags: ['physical'],
    action_fx: 'fx_fan_burst',
    trail_fx: 'trail_slash_arc',
    impact_fx: 'fx_impact_slash',
    proc_fx: 'status_bleed', proc_chance: 0.35,
  },

  // ──────────────────────────────────────────────────────────────
  // MAGE'S THEMED WEAPONS (3 extra)
  // ──────────────────────────────────────────────────────────────
  frost_bolt: {
    tier: 'basic', name: '빙결 화살', exclusive: 'mage',
    icon: 'icon_frost_bolt', sprite: 'proj_frost_bolt',
    pattern: 'aimed', count: 1, pierce: 3, homing: true,
    blurb: '빙결 결정 화살. 적중 시 100% 둔화, 누적 시 빙결.',
    tags: ['ice', 'arcane'],
    muzzle_fx: 'fx_muzzle_arcane',
    trail_fx: 'trail_proj',
    impact_fx: 'fx_impact_arcane',
    proc_fx: 'status_freeze', proc_chance: 0.4,
  },
  void_sphere: {
    tier: 'basic', name: '공허 구체', exclusive: 'mage',
    icon: 'icon_void_sphere', sprite: 'proj_void_sphere',
    pattern: 'pull', count: 1, duration: 3, radius: 80,
    blurb: '땅에 떨어뜨리는 작은 블랙홀. 적을 빨아들이고 피해.',
    tags: ['shadow', 'arcane'],
    action_fx: 'fx_void_pull',
    cast_fx: 'fx_summon_circle',
    aoe_fx: 'fx_void_pull',
    impact_fx: 'fx_impact_arcane',
    proc_fx: 'status_slow', proc_chance: 1,
  },
  arcane_missile: {
    tier: 'basic', name: '아케인 미사일', exclusive: 'mage',
    icon: 'icon_arcane_missile', sprite: 'proj_arcane_missile',
    pattern: 'volley', count: 6, pierce: 1, homing: true,
    blurb: '6발의 추적 마법구. 적당히 무작위 분산되어 각자 적을 추적.',
    tags: ['arcane'],
    cast_fx: 'fx_summon_circle',
    muzzle_fx: 'fx_muzzle_arcane',
    trail_fx: 'trail_proj',
    impact_fx: 'fx_impact_arcane',
    proc_fx: 'fx_explosion', proc_chance: 0.15,
  },

  // ──────────────────────────────────────────────────────────────
  // HUNTRESS'S THEMED WEAPONS (3 extra)
  // ──────────────────────────────────────────────────────────────
  crossbow_bolt: {
    tier: 'basic', name: '석궁 볼트', exclusive: 'huntress',
    icon: 'icon_crossbow_bolt', sprite: 'proj_crossbow_bolt',
    pattern: 'aimed', count: 1, pierce: 5, knockback: 6,
    blurb: '강력한 직선 볼트. 5명 관통 + 보스 추가 피해.',
    tags: ['physical'],
    muzzle_fx: 'fx_muzzle_arcane',
    trail_fx: 'trail_arrow',
    impact_fx: 'fx_impact_pierce',
    proc_fx: 'status_bleed', proc_chance: 0.4,
  },
  snare_trap: {
    tier: 'basic', name: '올가미 함정', exclusive: 'huntress',
    icon: 'icon_snare_trap', sprite: 'proj_snare_trap',
    pattern: 'static', count: 3, radius: 48, duration: 8,
    blurb: '플레이어 뒤에 함정 3개 설치. 적이 밟으면 4초간 둔화 + 출혈.',
    tags: ['nature', 'physical'],
    cast_fx: 'fx_summon_circle',
    aoe_fx: 'fx_snare_zone',
    impact_fx: 'fx_impact_pierce',
    proc_fx: 'status_slow', proc_chance: 1,
  },
  hunting_hawk: {
    tier: 'basic', name: '사냥매', exclusive: 'huntress',
    icon: 'icon_hunting_hawk', sprite: 'proj_hunting_hawk',
    pattern: 'summon', count: 1, pierce: 999, duration: 99,
    blurb: '플레이어를 따라다니는 매. 자동으로 가장 강한 적을 공격해 출혈.',
    tags: ['physical', 'nature'],
    action_fx: 'fx_soul_wisp',
    impact_fx: 'fx_impact_slash',
    proc_fx: 'status_bleed', proc_chance: 0.6,
  },

  // ──────────────────────────────────────────────────────────────
  // CLERIC'S THEMED WEAPONS (3 extra)
  // ──────────────────────────────────────────────────────────────
  heal_beam: {
    tier: 'basic', name: '치유의 빛줄기', exclusive: 'cleric',
    icon: 'icon_heal_beam', sprite: 'proj_heal_beam',
    pattern: 'beam', count: 1, pierce: 999, duration: 1.0,
    blurb: '플레이어와 연결되는 신성 빛줄기. 적은 태우고 자신은 회복.',
    tags: ['holy'],
    action_fx: 'fx_beam',
    cast_fx: 'fx_muzzle_holy',
    impact_fx: 'fx_impact_holy',
    drain_fx: 'fx_soul_wisp',
    proc_fx: 'status_burn', proc_chance: 0.5,
  },
  smite: {
    tier: 'basic', name: '천벌', exclusive: 'cleric',
    icon: 'icon_smite', sprite: 'proj_smite',
    pattern: 'rain', count: 3, pierce: 999, duration: 1.5,
    blurb: '하늘에서 신성 기둥 3개가 내리친다. 적중 자리에 광역 신성 피해.',
    tags: ['holy', 'lightning'],
    cast_fx: 'fx_summon_circle',
    aoe_fx: 'fx_smite_strike',
    impact_fx: 'fx_impact_holy',
    proc_fx: 'status_stun', proc_chance: 0.5,
  },
  sanctuary: {
    tier: 'basic', name: '성역 의식', exclusive: 'cleric',
    icon: 'icon_sanctuary', sprite: 'proj_sanctuary',
    pattern: 'static', radius: 96, duration: 8,
    blurb: '플레이어 발 밑에 성역 — 안에 있으면 매초 회복, 적은 진입 시 신성 피해.',
    tags: ['holy', 'nature'],
    action_fx: 'fx_heal_zone',
    aoe_fx: 'fx_heal_zone',
    impact_fx: 'fx_impact_holy',
    proc_fx: 'status_shield', proc_chance: 0.3,
  },
};
